[package]
name = "snark_wrapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derivative = "2"

franklin_crypto = {package = "franklin-crypto", features = ["plonk"], path = "../franklin-crypto"}
rescue_poseidon = {path = "../rescue-poseidon"}

# boojum = {git = "https://github.com/matter-5labs/boojum.git", branch = "main"}
boojum = { path = "../boojum" }
